name: Build and Push

inputs:
  platform:
    description: the platform to build the Docker image for
    type: enum
    required: true
    options:
      - amd64
      - arm64

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a # v3.11.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        push: true
        platforms: linux/${{ inputs.platform }}
        tags: ghcr.io/eraz1997/kiwi:${{ github.ref_name }}-${{ inputs.platform }}
