name: Test

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Run Tests
        uses: ./.github/workflows/composite/test.yaml
  
  check-version:
    runs-on: ubuntu-latest
    name: Check Version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check Greater Than latest
        run: |
          latest_version=$(gh release view --json tagName -q .tagName || echo "0.0.0")
          newest_version=$(printf "%s\n%s" "$latest_version" "${{ github.ref_name }}" | sort -V | tail -n1)

          if [[ "${{ github.ref_name }}" != "$newest_version" ]]; then
            echo "Tag is not newer than the latest release" >> /dev/stderr
            exit 1
          fi
      
      - name: Check Web Package Version
        run: |
          web_version=$(cat web/package.json | jq -r ".version")

          if [[ "${{ github.ref_name }}" != "$web_version" ]]; then
            echo "Web package version does not match tag" >> /dev/stderr
            exit 1
          fi
      
      - name: Check Backend Package Version
        run: |
          backend_version=$(awk -F' *= *' '
            $0 ~ /^\[package\]/ { in_package=1; next }
            in_package && $1 ~ /^version$/ {
              gsub(/["'\'']/, "", $2); print $2; exit
            }
          ' backend/Cargo.toml)

          if [[ "${{ github.ref_name }}" != "$backend_version" ]]; then
            echo "Backend package version does not match tag" >> /dev/stderr
            exit 1
          fi

  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push
    needs:
      - test
      - check-version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@05340d1c670183e7caabdb33ae9f1c80fae3b0c2 # v3.6.0
        with:
          platforms: arm64
          image: docker.io/tonistiigi/binfmt@sha256:1b804311fe87047a4c96d38b4b3ef6f62fca8cd125265917a9e3dc3c996c39e6 # qemu-v9.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a # v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/Eraz1997/kiwi:${{ github.ref_name }}

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs:
      - build-and-push

    steps:
      - name: Generate Changelog
        run: |
          latest_version_commit=$(git rev-parse "$(gh release view --json tagName -q .tagName)")
          if [[ "$latest_version_commit" == "" ]]; then
            git log --pretty=format:"%s" > /tmp/changelog.txt
          else
            git log $latest_version_commit..${{ github.sha }} --pretty=format:"%s" > /tmp/changelog.txt
          fi

      - name: Publish
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # 2.3.3
        with:
          body_path: /tmp/changelog.txt

