name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Node
        run: |
          curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir ~/.fnm --skip-shell
          echo "$HOME/.fnm" >> $GITHUB_PATH
          export PATH="$PATH:$HOME/.fnm"
          eval "$(fnm env)"
          fnm install --corepack-enabled 22

      - name: Install Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Lint Web
        run: |
          cd web
          eval "$(fnm env)"
          fnm use 22
          pnpm install
          pnpm prettier . --check
          pnpm eslint .
          pnpm tsc
          cd ..

      - name: Lint Backend
        run: |
          cd backend
          cargo fmt --check
          cargo clippy -- --deny warnings
          cd ..
